print('Oiê! Aqui é o Robby :P')
print('Me diga seu nome completo, assim lhe darei algumas informações!')
nome = str(input('Digite seu nome completo: ')).strip()
print(' ')
print('Analisando seu nome...')
print(f'Seu nome em MAIÚSCULAS é {nome.upper()}.')
print(f'Seu nome em minúsculas é {nome.lower()}.')
nomeR = nome.replace(' ', '')
print(f'Seu nome tem ao todo {len(nomeR)} letras.')
dividido = nome.split()
print(f'Seu primeiro nome é {dividido[0]} e ele tem {len(dividido[0])} letras.')
