print('Olá, eu sou o Robby :P')
print('Quem eu sou? Isso não importa agora :P')
nome = input('Qual é seu nome? ')
print('É um prazer te conhecer,', nome, '!')
print('Vamos ser bons amigos,', nome, '!')
