print('Oi! Aqui é o Robby :P')
print('Estava pensando sobre conversão de distâncias!')
print('Que tal me dizer um valor em metros convertê-lo!\n')
m = float(input('Valor em metros: '))
print(f'Esse valor em milímetros é {m * 1000}mm.')
print(f'Esse valor em centímetros é {m * 100}cm.')
print(f'Esse valor em decímetros é {m * 10}dm.')
print(f'Esse valor em decâmetros é {m / 10}dam.')
print(f'Esse valor em hectometros é {m / 100}hm.')
print(f'Esse valor em quilometros é {m / 1000}km.\n')
print('Ufa! É isso! :P')
