print('Hi! Aqui é o Robby :P')
print('Digite um número abaixo, que vou dizer seu dobro, triplo e até a sua raiz quadrada ;)\n')
n = int(input('Digite um número: '))
print(f'O dobro de {n} é {n * 2}.')
print(f'O triplo de {n} é {n * 3}.')
print(f'E por fim a raiz quadrada de {n} é {n ** (1/2):.2f}.')
