print('Hi, this is Robby :P')
print('Vamos converter R$ para U$(Dólar), €(Euro), £(Libra) e ¥(Iene)!\n')
m = float(input('Quantos R$ você tem? R$'))
print(f'Com R${m:.2f} você pode comprar {m / 5.08:.2f}U$.')
print(f'Com R${m:.2f} você pode comprar {m / 5.29:.2f}€.')
print(f'Com R${m:.2f} você pode comprar {m / 6.23:.2f}£.')
print(f'Com R${m:.2f} você pode comprar {m / 0.0393:.2f}¥.')
